---
server:
    install: "1"
    packages: [htop, git, mc, gcc, autoconf, re2c, make, automake, libpcre3, libpcre3-dev, libssl1.0.0, libssl-dev, libcurl3, libcurl4-openssl-dev]
    timezone: Europe/Kiev
    locale: en_US.UTF-8
    domain: "stepic.lan"
vagrant_local:
    install: "1"
    vm:
        hostname: "{{server.domain}}"

nginx_sendfile: "off"